insert into forum(title) values ('Some forum');
insert into topic (title, forum_id) values ('ipsum consequat', 1);
insert into topic (title, forum_id) values ('velit ipsum', 1);

insert into priority_status(name) values ('High');
insert into priority_status(name) values ('Normal');
insert into priority_status(name) values ('Low');

insert into progress_status(name) values ('Registered');
insert into progress_status(name) values ('Free');
insert into progress_status(name) values ('Joined');
insert into progress_status(name) values ('In progress');
insert into progress_status(name) values ('Closed');
insert into progress_status(name) values ('Reopen');

insert into "user" (first_name, last_name, second_name, password, email, date_of_birth, phone_number, role) values ('Wayne', 'Collins', 'Wayneovich', '69r0fk61Pe1', 'wcollins0@aboutads.info', '1985-12-12', '374-(251)803-9567', 'admin');
insert into "user" (first_name, last_name, second_name, password, email, date_of_birth, phone_number, role) values ('Denise', 'Day', 'Deniseovich', 'a9IRit27', 'dday1@blogtalkradio.com', '1995-11-27', '241-(539)668-2990', 'admin');
insert into "user" (first_name, last_name, second_name, password, email, date_of_birth, phone_number, role) values ('Russell', 'Warren', 'Russellovich', '8raqXOh86B', 'rwarren2@imgur.com', '1983-04-17', '55-(451)203-7493', 'admin');
insert into "user" (first_name, last_name, second_name, password, email, date_of_birth, phone_number, role) values ('Norma', 'Cole', 'Normaovich', '2pQ7j5C4XRM3', 'ncole3@huffingtonpost.com', '1988-11-08', '86-(418)990-2646', 'office manager');
insert into "user" (first_name, last_name, second_name, password, email, date_of_birth, phone_number, role) values ('Henry', 'Brooks', 'Henryovich', '86864qr05f', 'hbrooks4@kickstarter.com', '1984-11-03', '55-(701)966-4268', 'office manager');
insert into "user" (first_name, last_name, second_name, password, email, date_of_birth, phone_number, role) values ('Matthew', 'Reyes', 'Matthewovich', 'cm62xd035', 'mreyes5@flickr.com', '1984-02-06', '66-(509)508-9882', 'office manager');
insert into "user" (first_name, last_name, second_name, password, email, date_of_birth, phone_number, role) values ('Clarence', 'Stone', 'Clarenceovich', '317772cED24B', 'cstone6@infoseek.co.jp', '1991-11-11', '380-(331)922-1800', 'office manager');
insert into "user" (first_name, last_name, second_name, password, email, date_of_birth, phone_number, role) values ('Dorothy', 'Collins', 'Dorothyovich', '4212312FA', 'dcollins7@ed.gov', '1980-10-12', '380-(874)642-9009', 'office manager');
insert into "user" (first_name, last_name, second_name, password, email, date_of_birth, phone_number, role) values ('Catherine', 'Meyer', 'Catherineovich', '559Cx200', 'cmeyer8@twitpic.com', '1990-09-29', '7-(933)150-8917', 'office manager');
insert into "user" (first_name, last_name, second_name, password, email, date_of_birth, phone_number, role) values ('Margaret', 'Fields', 'Margaretovich', 'KU2509OC51Ns', 'mfields9@miibeian.gov.cn', '1985-05-12', '60-(626)633-6436', 'office manager');
insert into "user" (first_name, last_name, second_name, password, email, date_of_birth, phone_number, role) values ('Dorothy', 'Fox', 'Dorothyovich', 'GqyN79B6w07', 'dfoxa@geocities.com', '1984-11-15', '86-(998)372-3112', 'office manager');
insert into "user" (first_name, last_name, second_name, password, email, date_of_birth, phone_number, role) values ('Teresa', 'Castillo', 'Teresaovich', 'a27y7Qhmb4', 'tcastillob@jigsy.com', '1983-05-04', '380-(529)417-8373', 'office manager');
insert into "user" (first_name, last_name, second_name, password, email, date_of_birth, phone_number, role) values ('Kelly', 'Richards', 'Kellyovich', '8rlSHYR3mgC', 'krichardsc@mediafire.com', '1998-04-17', '33-(269)123-3342', 'office manager');
insert into "user" (first_name, last_name, second_name, password, email, date_of_birth, phone_number, role) values ('Louis', 'Wallace', 'Louisovich', 'j5109Q8vI39A', 'lwallaced@weather.com', '1988-01-07', '81-(543)113-3548', 'office manager');
insert into "user" (first_name, last_name, second_name, password, email, date_of_birth, phone_number, role) values ('Gary', 'Brooks', 'Garyovich', 't727H142p1r3', 'gbrookse@eventbrite.com', '1995-06-11', '86-(985)394-5067', 'office manager');
insert into "user" (first_name, last_name, second_name, password, email, date_of_birth, phone_number, role) values ('Jesse', 'Collins', 'Jesseovich', '0H4190S90', 'jcollinsf@samsung.com', '1985-04-08', '212-(838)756-5496', 'office manager');
insert into "user" (first_name, last_name, second_name, password, email, date_of_birth, phone_number, role) values ('Lillian', 'Wells', 'Lillianovich', '71z7Xh03wNg', 'lwellsg@ifeng.com', '1990-03-14', '502-(712)285-4471', 'office manager');
insert into "user" (first_name, last_name, second_name, password, email, date_of_birth, phone_number, role) values ('Frank', 'Wagner', 'Frankovich', '35T2R1FU', 'fwagnerh@hhs.gov', '1980-09-02', '1-(755)536-1935', 'office manager');
insert into "user" (first_name, last_name, second_name, password, email, date_of_birth, phone_number, role) values ('Evelyn', 'Murray', 'Evelynovich', '48f5NB2rZ', 'emurrayi@uol.com.br', '1996-09-20', '351-(497)449-5423', 'office manager');
insert into "user" (first_name, last_name, second_name, password, email, date_of_birth, phone_number, role) values ('Gerald', 'Richards', 'Geraldovich', 'v6tue6629', 'grichardsj@sbwire.com', '1999-05-13', '353-(210)218-6601', 'office manager');
insert into "user" (first_name, last_name, second_name, password, email, date_of_birth, phone_number, role) values ('Anna', 'Watson', 'Annaovich', 'KGR8E4M6', 'awatsonk@engadget.com', '1985-01-12', '7-(835)480-0496', 'office manager');
insert into "user" (first_name, last_name, second_name, password, email, date_of_birth, phone_number, role) values ('Kathryn', 'Pierce', 'Kathrynovich', '0YBA6dDL', 'kpiercel@wisc.edu', '1985-08-13', '63-(858)171-2498', 'office manager');
insert into "user" (first_name, last_name, second_name, password, email, date_of_birth, phone_number, role) values ('William', 'Baker', 'Williamovich', 'idK926541fP2', 'wbakerm@amazon.com', '1985-01-11', '48-(538)901-8263', 'office manager');
insert into "user" (first_name, last_name, second_name, password, email, date_of_birth, phone_number, role) values ('Raymond', 'Berry', 'Raymondovich', 'cNR3z1BL5', 'rberryn@whitehouse.gov', '1994-02-28', '351-(387)125-9198', 'office manager');
insert into "user" (first_name, last_name, second_name, password, email, date_of_birth, phone_number, role) values ('Kevin', 'Cruz', 'Kevinovich', '17OBh4xk', 'kcruzo@prweb.com', '1988-03-31', '62-(837)474-9424', 'office manager');
insert into "user" (first_name, last_name, second_name, password, email, date_of_birth, phone_number, role) values ('Kelly', 'Ward', 'Kellyovich', 'hM5ML07r', 'kwardp@wikia.com', '1998-01-15', '86-(752)977-3644', 'office manager');
insert into "user" (first_name, last_name, second_name, password, email, date_of_birth, phone_number, role) values ('Laura', 'Simmons', 'Lauraovich', '5U15wm85YCJ', 'lsimmonsq@berkeley.edu', '1980-07-30', '54-(234)315-9613', 'office manager');
insert into "user" (first_name, last_name, second_name, password, email, date_of_birth, phone_number, role) values ('Ryan', 'Warren', 'Ryanovich', '50V3185736', 'rwarrenr@dyndns.org', '1995-04-05', '389-(827)211-0290', 'office manager');
insert into "user" (first_name, last_name, second_name, password, email, date_of_birth, phone_number, role) values ('Gregory', 'Flores', 'Gregoryovich', '7948wcv1', 'gfloress@about.me', '1992-10-04', '63-(859)322-9711', 'office manager');
insert into "user" (first_name, last_name, second_name, password, email, date_of_birth, phone_number, role) values ('Katherine', 'Ward', 'Katherineovich', 'vN891704y', 'kwardt@cargocollective.com', '1999-12-08', '86-(152)935-0805', 'office manager');
insert into "user" (first_name, last_name, second_name, password, email, date_of_birth, phone_number, role) values ('Christopher', 'Cox', 'Christopherovich', 'qNjsEKRE69', 'ccoxu@pcworld.com', '1994-03-16', '86-(267)263-0880', 'office manager');
insert into "user" (first_name, last_name, second_name, password, email, date_of_birth, phone_number, role) values ('Patricia', 'Payne', 'Patriciaovich', 'M47w3JV7Cd', 'ppaynev@e-recht24.de', '1997-07-31', '86-(866)362-6741', 'office manager');
insert into "user" (first_name, last_name, second_name, password, email, date_of_birth, phone_number, role) values ('Jesse', 'Rivera', 'Jesseovich', '1H9OB78p5K6', 'jriveraw@mlb.com', '1984-02-13', '7-(839)235-1140', 'office manager');
insert into "user" (first_name, last_name, second_name, password, email, date_of_birth, phone_number, role) values ('Anna', 'Ramos', 'Annaovich', '32oiIg96s', 'aramosx@patch.com', '1983-05-06', '63-(117)643-0111', 'office manager');
insert into "user" (first_name, last_name, second_name, password, email, date_of_birth, phone_number, role) values ('Eric', 'Bennett', 'Ericovich', '6N6iZ45enn57', 'ebennetty@ihg.com', '1991-06-30', '48-(878)811-3844', 'office manager');
insert into "user" (first_name, last_name, second_name, password, email, date_of_birth, phone_number, role) values ('Jean', 'Hernandez', 'Jeanovich', '35876413', 'jhernandezz@ucoz.com', '1992-01-22', '62-(730)348-6302', 'office manager');
insert into "user" (first_name, last_name, second_name, password, email, date_of_birth, phone_number, role) values ('Peter', 'Jacobs', 'Peterovich', '4u8491BiX0XO', 'pjacobs10@vimeo.com', '1988-01-09', '62-(322)359-5074', 'office manager');
insert into "user" (first_name, last_name, second_name, password, email, date_of_birth, phone_number, role) values ('Frank', 'Smith', 'Frankovich', '6235QU847j54', 'fsmith11@zimbio.com', '1998-05-11', '86-(651)765-0221', 'office manager');
insert into "user" (first_name, last_name, second_name, password, email, date_of_birth, phone_number, role) values ('Arthur', 'Castillo', 'Arthurovich', '95z04Qde7', 'acastillo12@blogs.com', '1988-10-19', '44-(334)408-4285', 'office manager');
insert into "user" (first_name, last_name, second_name, password, email, date_of_birth, phone_number, role) values ('Victor', 'Jones', 'Victorovich', '522Q87Z9GV90', 'vjones13@prnewswire.com', '1991-04-08', '46-(154)225-3706', 'office manager');
insert into "user" (first_name, last_name, second_name, password, email, date_of_birth, phone_number, role) values ('Justin', 'Nichols', 'Justinovich', 'M0wG49vu', 'jnichols14@tuttocitta.it', '1993-05-24', '47-(851)274-8604', 'employee');
insert into "user" (first_name, last_name, second_name, password, email, date_of_birth, phone_number, role) values ('Sandra', 'Day', 'Sandraovich', '2i56Is6W48', 'sday15@globo.com', '1991-02-21', '212-(503)646-0396', 'employee');
insert into "user" (first_name, last_name, second_name, password, email, date_of_birth, phone_number, role) values ('Lisa', 'Williams', 'Lisaovich', 'Xz598Q5z7', 'lwilliams16@amazon.com', '1982-11-06', '7-(143)438-5690', 'employee');
insert into "user" (first_name, last_name, second_name, password, email, date_of_birth, phone_number, role) values ('Edward', 'Wheeler', 'Edwardovich', 'KLdq5rH178', 'ewheeler17@discovery.com', '1998-08-20', '62-(430)855-2371', 'employee');
insert into "user" (first_name, last_name, second_name, password, email, date_of_birth, phone_number, role) values ('Emily', 'Butler', 'Emilyovich', 'wK10cT4A0', 'ebutler18@latimes.com', '1986-12-15', '57-(206)341-5496', 'employee');
insert into "user" (first_name, last_name, second_name, password, email, date_of_birth, phone_number, role) values ('Donald', 'Peterson', 'Donaldovich', '3c6JXjO330H7', 'dpeterson19@cnn.com', '1991-03-25', '52-(762)780-3570', 'employee');
insert into "user" (first_name, last_name, second_name, password, email, date_of_birth, phone_number, role) values ('Aaron', 'Riley', 'Aaronovich', '6404bYJyN', 'ariley1a@vimeo.com', '1999-05-18', '256-(783)547-8954', 'employee');
insert into "user" (first_name, last_name, second_name, password, email, date_of_birth, phone_number, role) values ('Jason', 'Richards', 'Jasonovich', '27w66S19', 'jrichards1b@e-recht24.de', '1985-08-25', '86-(543)949-4354', 'employee');
insert into "user" (first_name, last_name, second_name, password, email, date_of_birth, phone_number, role) values ('Justin', 'Phillips', 'Justinovich', 'dO842X452', 'jphillips1c@discovery.com', '1998-12-06', '63-(194)997-3489', 'employee');
insert into "user" (first_name, last_name, second_name, password, email, date_of_birth, phone_number, role) values ('Katherine', 'Carpenter', 'Katherineovich', 'gBB11K4G9X6', 'kcarpenter1d@youku.com', '1981-02-18', '62-(756)369-8444', 'employee');
insert into "user" (first_name, last_name, second_name, password, email, date_of_birth, phone_number, role) values ('Christopher', 'Riley', 'Christopherovich', '87La2521', 'criley1e@go.com', '1994-10-14', '44-(733)461-6883', 'employee');
insert into "user" (first_name, last_name, second_name, password, email, date_of_birth, phone_number, role) values ('Lawrence', 'Anderson', 'Lawrenceovich', '78r1S0q7', 'landerson1f@webs.com', '1986-10-09', '48-(701)293-5135', 'employee');
insert into "user" (first_name, last_name, second_name, password, email, date_of_birth, phone_number, role) values ('Irene', 'West', 'Ireneovich', 'e34gGm9l1', 'iwest1g@netlog.com', '1995-09-24', '60-(183)507-8124', 'employee');
insert into "user" (first_name, last_name, second_name, password, email, date_of_birth, phone_number, role) values ('Teresa', 'Adams', 'Teresaovich', 'tOY426ew869', 'tadams1h@blogger.com', '1988-12-03', '86-(634)319-1491', 'employee');
insert into "user" (first_name, last_name, second_name, password, email, date_of_birth, phone_number, role) values ('Anthony', 'Gilbert', 'Anthonyovich', '4ofS1z27', 'agilbert1i@devhub.com', '1993-01-05', '351-(518)100-9554', 'employee');
insert into "user" (first_name, last_name, second_name, password, email, date_of_birth, phone_number, role) values ('Phillip', 'Hawkins', 'Phillipovich', '6e3M072wJu', 'phawkins1j@simplemachines.org', '1987-01-21', '7-(969)513-5581', 'employee');
insert into "user" (first_name, last_name, second_name, password, email, date_of_birth, phone_number, role) values ('Elizabeth', 'Cunningham', 'Elizabethovich', 'm4J348GF', 'ecunningham1k@nydailynews.com', '1980-03-22', '62-(273)403-8435', 'employee');
insert into "user" (first_name, last_name, second_name, password, email, date_of_birth, phone_number, role) values ('Lois', 'Stewart', 'Loisovich', 'Ot80IOfDj', 'lstewart1l@infoseek.co.jp', '1988-01-19', '420-(972)378-3794', 'employee');
insert into "user" (first_name, last_name, second_name, password, email, date_of_birth, phone_number, role) values ('Sara', 'Mitchell', 'Saraovich', 'YOqLY1c8', 'smitchell1m@theatlantic.com', '1989-06-08', '1-(850)678-1379', 'employee');
insert into "user" (first_name, last_name, second_name, password, email, date_of_birth, phone_number, role) values ('Bonnie', 'Stevens', 'Bonnieovich', 'rIag7VBR382', 'bstevens1n@go.com', '1991-03-21', '62-(829)314-0896', 'employee');
insert into "user" (first_name, last_name, second_name, password, email, date_of_birth, phone_number, role) values ('Brenda', 'Little', 'Brendaovich', 'Z5r93Lp3ULr3', 'blittle1o@bizjournals.com', '1996-07-12', '86-(480)666-6210', 'employee');
insert into "user" (first_name, last_name, second_name, password, email, date_of_birth, phone_number, role) values ('Carl', 'Dixon', 'Carlovich', '9oS3E14M9Yg', 'cdixon1p@bigcartel.com', '1985-03-14', '86-(939)330-7576', 'employee');
insert into "user" (first_name, last_name, second_name, password, email, date_of_birth, phone_number, role) values ('Carol', 'Rogers', 'Carolovich', '0a8184d1', 'crogers1q@gnu.org', '1986-02-08', '1-(816)549-2991', 'employee');
insert into "user" (first_name, last_name, second_name, password, email, date_of_birth, phone_number, role) values ('Sean', 'Payne', 'Seanovich', '3241682yh7L5', 'spayne1r@army.mil', '1999-03-26', '1-(991)386-9383', 'employee');
insert into "user" (first_name, last_name, second_name, password, email, date_of_birth, phone_number, role) values ('Brandon', 'Collins', 'Brandonovich', '265FK9A1311', 'bcollins1s@skype.com', '1983-08-25', '51-(708)414-9661', 'employee');
insert into "user" (first_name, last_name, second_name, password, email, date_of_birth, phone_number, role) values ('Eugene', 'Rodriguez', 'Eugeneovich', '8Tm59070a', 'erodriguez1t@si.edu', '1993-09-24', '358-(363)530-0241', 'employee');
insert into "user" (first_name, last_name, second_name, password, email, date_of_birth, phone_number, role) values ('Angela', 'Little', 'Angelaovich', '828C3665', 'alittle1u@wix.com', '1989-08-18', '86-(572)819-1326', 'employee');
insert into "user" (first_name, last_name, second_name, password, email, date_of_birth, phone_number, role) values ('Sandra', 'Peterson', 'Sandraovich', 'f7m03V80M', 'speterson1v@printfriendly.com', '1989-01-22', '358-(998)405-9689', 'employee');
insert into "user" (first_name, last_name, second_name, password, email, date_of_birth, phone_number, role) values ('Lori', 'Rivera', 'Loriovich', 'SSZSd4tBV', 'lrivera1w@home.pl', '1986-06-29', '62-(928)664-7849', 'employee');
insert into "user" (first_name, last_name, second_name, password, email, date_of_birth, phone_number, role) values ('Benjamin', 'Robinson', 'Benjaminovich', '79ZL48c2k', 'brobinson1x@sourceforge.net', '1982-02-21', '267-(654)812-6897', 'employee');
insert into "user" (first_name, last_name, second_name, password, email, date_of_birth, phone_number, role) values ('Walter', 'Williamson', 'Walterovich', 'x6K4c8Pb55', 'wwilliamson1y@mediafire.com', '1980-12-01', '224-(148)415-8303', 'employee');
insert into "user" (first_name, last_name, second_name, password, email, date_of_birth, phone_number, role) values ('Kenneth', 'Elliott', 'Kennethovich', 'FV3f6BgAz1', 'kelliott1z@chronoengine.com', '1991-08-04', '226-(217)671-7869', 'employee');
insert into "user" (first_name, last_name, second_name, password, email, date_of_birth, phone_number, role) values ('Louise', 'Day', 'Louiseovich', '6A8544545D', 'lday20@washingtonpost.com', '1992-08-02', '63-(162)270-6127', 'employee');
insert into "user" (first_name, last_name, second_name, password, email, date_of_birth, phone_number, role) values ('Helen', 'Kim', 'Helenovich', '1W71901FC', 'hkim21@cocolog-nifty.com', '1982-02-19', '963-(774)668-0883', 'employee');
insert into "user" (first_name, last_name, second_name, password, email, date_of_birth, phone_number, role) values ('Gloria', 'Fox', 'Gloriaovich', 't5SL813e', 'gfox22@nps.gov', '1982-06-26', '86-(592)613-7332', 'employee');
insert into "user" (first_name, last_name, second_name, password, email, date_of_birth, phone_number, role) values ('Todd', 'Hayes', 'Toddovich', '1150Kalp', 'thayes23@wix.com', '1994-05-06', '505-(312)656-6233', 'employee');
insert into "user" (first_name, last_name, second_name, password, email, date_of_birth, phone_number, role) values ('Janice', 'Green', 'Janiceovich', '79If46yO968S', 'jgreen24@hugedomains.com', '1995-12-28', '1-(260)517-3966', 'employee');
insert into "user" (first_name, last_name, second_name, password, email, date_of_birth, phone_number, role) values ('Donald', 'Hayes', 'Donaldovich', '919m0E3Qs65A', 'dhayes25@360.cn', '1997-09-18', '62-(352)708-0129', 'employee');
insert into "user" (first_name, last_name, second_name, password, email, date_of_birth, phone_number, role) values ('Frances', 'Stevens', 'Francesovich', 'cn962DKVyO5', 'fstevens26@accuweather.com', '1985-10-24', '386-(474)727-6786', 'employee');
insert into "user" (first_name, last_name, second_name, password, email, date_of_birth, phone_number, role) values ('Cynthia', 'Rivera', 'Cynthiaovich', 'V261I43gWW', 'crivera27@weebly.com', '1981-05-03', '55-(316)196-0166', 'employee');
insert into "user" (first_name, last_name, second_name, password, email, date_of_birth, phone_number, role) values ('Brian', 'Greene', 'Brianovich', 'iXAHg4vkh', 'bgreene28@cornell.edu', '1982-02-08', '86-(374)917-6385', 'employee');
insert into "user" (first_name, last_name, second_name, password, email, date_of_birth, phone_number, role) values ('Charles', 'Baker', 'Charlesovich', '5ztm4q951', 'cbaker29@paginegialle.it', '1988-03-21', '7-(905)479-5327', 'employee');
insert into "user" (first_name, last_name, second_name, password, email, date_of_birth, phone_number, role) values ('Joshua', 'Davis', 'Joshuaovich', 's927Y2uC', 'jdavis2a@apache.org', '1980-11-03', '56-(885)324-5558', 'employee');
insert into "user" (first_name, last_name, second_name, password, email, date_of_birth, phone_number, role) values ('Joe', 'Roberts', 'Joeovich', 'K9Zp6zF3D1q', 'jroberts2b@drupal.org', '1986-10-28', '7-(180)859-6629', 'employee');
insert into "user" (first_name, last_name, second_name, password, email, date_of_birth, phone_number, role) values ('Martha', 'Fuller', 'Marthaovich', 'qhLFh22sD2v', 'mfuller2c@si.edu', '1996-08-16', '62-(741)482-1888', 'employee');
insert into "user" (first_name, last_name, second_name, password, email, date_of_birth, phone_number, role) values ('Chris', 'Howard', 'Chrisovich', '9z59K4b9Zk14', 'choward2d@goodreads.com', '1986-09-22', '63-(184)586-9704', 'employee');
insert into "user" (first_name, last_name, second_name, password, email, date_of_birth, phone_number, role) values ('Christopher', 'Powell', 'Christopherovich', 'zBZ00561H5', 'cpowell2e@cocolog-nifty.com', '1980-02-22', '86-(871)673-5219', 'employee');
insert into "user" (first_name, last_name, second_name, password, email, date_of_birth, phone_number, role) values ('Charles', 'Medina', 'Charlesovich', '4Da41ib3Y79', 'cmedina2f@nationalgeographic.com', '1987-07-13', '46-(935)465-2407', 'employee');
insert into "user" (first_name, last_name, second_name, password, email, date_of_birth, phone_number, role) values ('Joseph', 'Lawson', 'Josephovich', '0wMxwT6p7a8', 'jlawson2g@columbia.edu', '1987-04-04', '965-(237)534-6379', 'employee');
insert into "user" (first_name, last_name, second_name, password, email, date_of_birth, phone_number, role) values ('Jacqueline', 'Johnston', 'Jacquelineovich', 'KH0atoI1M', 'jjohnston2h@deviantart.com', '1985-12-09', '86-(185)875-5072', 'employee');
insert into "user" (first_name, last_name, second_name, password, email, date_of_birth, phone_number, role) values ('Rachel', 'Knight', 'Rachelovich', 'I1u1pa3T', 'rknight2i@dyndns.org', '1983-02-18', '374-(479)540-9889', 'employee');
insert into "user" (first_name, last_name, second_name, password, email, date_of_birth, phone_number, role) values ('Steve', 'Miller', 'Steveovich', '4asrSNEpJ7O7', 'smiller2j@census.gov', '1995-09-07', '62-(602)544-4740', 'employee');
insert into "user" (first_name, last_name, second_name, password, email, date_of_birth, phone_number, role) values ('Nancy', 'Hunt', 'Nancyovich', '34170152', 'nhunt2k@blog.com', '1999-02-18', '81-(949)193-1741', 'employee');
insert into "user" (first_name, last_name, second_name, password, email, date_of_birth, phone_number, role) values ('Johnny', 'Bennett', 'Johnnyovich', '017X615o3w', 'jbennett2l@instagram.com', '1984-02-27', '66-(709)347-9230', 'employee');
insert into "user" (first_name, last_name, second_name, password, email, date_of_birth, phone_number, role) values ('Joshua', 'Stone', 'Joshuaovich', '66908mIM', 'jstone2m@etsy.com', '1983-11-23', '86-(893)281-9385', 'employee');
insert into "user" (first_name, last_name, second_name, password, email, date_of_birth, phone_number, role) values ('Douglas', 'Stanley', 'Douglasovich', 'G3203GXN', 'dstanley2n@simplemachines.org', '1995-03-06', '1-(681)299-1206', 'employee');
insert into "user" (first_name, last_name, second_name, password, email, date_of_birth, phone_number, role) values ('Eric', 'Grant', 'Ericovich', '43nJK6367dTr', 'egrant2o@fastcompany.com', '1992-12-24', '55-(339)160-9213', 'employee');
insert into "user" (first_name, last_name, second_name, password, email, date_of_birth, phone_number, role) values ('Louis', 'Fowler', 'Louisovich', '8l4b19lg2', 'lfowler2p@cdbaby.com', '1984-12-15', '86-(403)390-1556', 'employee');
insert into "user" (first_name, last_name, second_name, password, email, date_of_birth, phone_number, role) values ('Albert', 'Washington', 'Albertovich', '318610N9n', 'awashington2q@godaddy.com', '1996-04-23', '7-(414)638-3486', 'employee');
insert into "user" (first_name, last_name, second_name, password, email, date_of_birth, phone_number, role) values ('Justin', 'Harris', 'Justinovich', 'x6gjw4p549', 'jharris2r@delicious.com', '1988-04-20', '81-(368)868-2785', 'employee');

insert into request (title, description, priority_status_id, progress_status_id, reporter_id, assignee_id, estimate_time_in_days, date_of_creation, joined_request_id) values ('sapien in sapien', 'suspendisse ornare consequat lectus in est risus auctor', 4, 8, 101, 34, 5, '2017-02-08 21:04:00', null);
insert into request (title, description, priority_status_id, progress_status_id, reporter_id, assignee_id, estimate_time_in_days, date_of_creation, joined_request_id) values ('id turpis integer', 'aliquam augue quam sollicitudin vitae consectetuer eget', 5, 11, 80, 37, 1, '2017-02-07 04:21:15', null);
insert into request (title, description, priority_status_id, progress_status_id, reporter_id, assignee_id, estimate_time_in_days, date_of_creation, joined_request_id) values ('porttitor lacus at', 'dapibus nulla suscipit ligula in lacus curabitur at ipsum ac', 4, 9, 103, 27, 3, '2017-02-04 14:16:19', null);
insert into request (title, description, priority_status_id, progress_status_id, reporter_id, assignee_id, estimate_time_in_days, date_of_creation, joined_request_id) values ('tellus semper interdum', 'morbi ut odio cras mi pede malesuada', 4, 10, 96, 20, 7, '2017-02-05 01:27:16', null);
insert into request (title, description, priority_status_id, progress_status_id, reporter_id, assignee_id, estimate_time_in_days, date_of_creation, joined_request_id) values ('quis turpis eget', 'vel sem sed sagittis nam congue', 6, 10, 81, 22, 1, '2017-02-19 07:04:57', null);
insert into request (title, description, priority_status_id, progress_status_id, reporter_id, assignee_id, estimate_time_in_days, date_of_creation, joined_request_id) values ('congue diam id', 'cras non velit nec nisi vulputate nonummy maecenas', 6, 9, 92, 32, 6, '2017-02-01 14:24:00', null);
insert into request (title, description, priority_status_id, progress_status_id, reporter_id, assignee_id, estimate_time_in_days, date_of_creation, joined_request_id) values ('ut nunc vestibulum', 'et magnis dis parturient montes nascetur ridiculus', 6, 10, 74, 29, 3, '2017-02-12 17:33:43', null);
insert into request (title, description, priority_status_id, progress_status_id, reporter_id, assignee_id, estimate_time_in_days, date_of_creation, joined_request_id) values ('porttitor lacus at', 'dui vel nisl duis ac nibh', 6, 12, 65, 32, 3, '2017-02-18 04:43:16', null);
insert into request (title, description, priority_status_id, progress_status_id, reporter_id, assignee_id, estimate_time_in_days, date_of_creation, joined_request_id) values ('morbi ut odio', 'dignissim vestibulum vestibulum ante ipsum primis in', 6, 9, 67, 29, 6, '2017-02-17 22:30:25', null);
insert into request (title, description, priority_status_id, progress_status_id, reporter_id, assignee_id, estimate_time_in_days, date_of_creation, joined_request_id) values ('amet lobortis sapien', 'faucibus orci luctus et ultrices posuere cubilia', 6, 8, 57, 50, 6, '2017-02-14 09:22:49', null);
insert into request (title, description, priority_status_id, progress_status_id, reporter_id, assignee_id, estimate_time_in_days, date_of_creation, joined_request_id) values ('interdum mauris ullamcorper', 'quam a odio in hac', 5, 11, 75, 45, 1, '2017-02-16 07:58:42', null);
insert into request (title, description, priority_status_id, progress_status_id, reporter_id, assignee_id, estimate_time_in_days, date_of_creation, joined_request_id) values ('volutpat eleifend donec', 'at nunc commodo placerat praesent blandit nam nulla integer pede', 5, 11, 91, 42, 4, '2017-02-02 11:14:39', null);
insert into request (title, description, priority_status_id, progress_status_id, reporter_id, assignee_id, estimate_time_in_days, date_of_creation, joined_request_id) values ('in sagittis dui', 'quis tortor id nulla ultrices', 5, 12, 75, 48, 4, '2017-02-13 07:51:29', null);
insert into request (title, description, priority_status_id, progress_status_id, reporter_id, assignee_id, estimate_time_in_days, date_of_creation, joined_request_id) values ('platea dictumst aliquam', 'non lectus aliquam sit amet diam', 6, 10, 61, 21, 6, '2017-02-10 18:04:07', null);
insert into request (title, description, priority_status_id, progress_status_id, reporter_id, assignee_id, estimate_time_in_days, date_of_creation, joined_request_id) values ('pede venenatis non', 'velit vivamus vel nulla eget eros elementum pellentesque', 4, 7, 77, 19, 5, '2017-02-07 00:51:42', null);
insert into request (title, description, priority_status_id, progress_status_id, reporter_id, assignee_id, estimate_time_in_days, date_of_creation, joined_request_id) values ('nisi nam ultrices', 'nec molestie sed justo pellentesque viverra pede ac diam cras', 5, 10, 91, 48, 6, '2017-02-06 11:24:35', null);
insert into request (title, description, priority_status_id, progress_status_id, reporter_id, assignee_id, estimate_time_in_days, date_of_creation, joined_request_id) values ('aenean fermentum donec', 'eleifend quam a odio in hac habitasse platea', 4, 7, 63, 29, 2, '2017-02-12 11:52:27', null);
insert into request (title, description, priority_status_id, progress_status_id, reporter_id, assignee_id, estimate_time_in_days, date_of_creation, joined_request_id) values ('id mauris vulputate', 'est lacinia nisi venenatis tristique fusce congue diam', 4, 8, 95, 46, 6, '2017-02-01 10:51:41', null);
insert into request (title, description, priority_status_id, progress_status_id, reporter_id, assignee_id, estimate_time_in_days, date_of_creation, joined_request_id) values ('justo sit amet', 'primis in faucibus orci luctus', 6, 11, 87, 35, 6, '2017-02-02 01:06:47', null);
insert into request (title, description, priority_status_id, progress_status_id, reporter_id, assignee_id, estimate_time_in_days, date_of_creation, joined_request_id) values ('quis augue luctus', 'mauris lacinia sapien quis libero nullam', 6, 9, 68, 20, 1, '2017-02-15 04:16:11', null);
insert into request (title, description, priority_status_id, progress_status_id, reporter_id, assignee_id, estimate_time_in_days, date_of_creation, joined_request_id) values ('rhoncus aliquam lacus', 'sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl', 4, 7, 110, 29, 6, '2017-02-18 02:16:01', null);
insert into request (title, description, priority_status_id, progress_status_id, reporter_id, assignee_id, estimate_time_in_days, date_of_creation, joined_request_id) values ('odio in hac', 'molestie hendrerit at vulputate vitae nisl aenean', 4, 11, 83, 18, 4, '2017-02-15 19:31:03', null);
insert into request (title, description, priority_status_id, progress_status_id, reporter_id, assignee_id, estimate_time_in_days, date_of_creation, joined_request_id) values ('dignissim vestibulum vestibulum', 'pellentesque eget nunc donec quis orci', 5, 10, 63, 48, 7, '2017-02-03 01:55:45', null);
insert into request (title, description, priority_status_id, progress_status_id, reporter_id, assignee_id, estimate_time_in_days, date_of_creation, joined_request_id) values ('dapibus at diam', 'justo aliquam quis turpis eget elit', 5, 12, 94, 31, 6, '2017-02-07 09:59:55', null);
insert into request (title, description, priority_status_id, progress_status_id, reporter_id, assignee_id, estimate_time_in_days, date_of_creation, joined_request_id) values ('vulputate ut ultrices', 'neque duis bibendum morbi non', 5, 10, 57, 29, 6, '2017-02-17 21:45:02', null);
insert into request (title, description, priority_status_id, progress_status_id, reporter_id, assignee_id, estimate_time_in_days, date_of_creation, joined_request_id) values ('lacinia aenean sit', 'lectus in quam fringilla rhoncus mauris enim', 4, 10, 75, 48, 1, '2017-02-04 06:15:38', null);
insert into request (title, description, priority_status_id, progress_status_id, reporter_id, assignee_id, estimate_time_in_days, date_of_creation, joined_request_id) values ('nam tristique tortor', 'in hac habitasse platea dictumst morbi vestibulum velit id', 6, 8, 68, 21, 5, '2017-02-13 23:38:26', null);
insert into request (title, description, priority_status_id, progress_status_id, reporter_id, assignee_id, estimate_time_in_days, date_of_creation, joined_request_id) values ('in consequat ut', 'a suscipit nulla elit ac nulla sed vel enim sit', 6, 11, 109, 52, 6, '2017-02-13 23:26:25', null);
insert into request (title, description, priority_status_id, progress_status_id, reporter_id, assignee_id, estimate_time_in_days, date_of_creation, joined_request_id) values ('nisl nunc nisl', 'ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit', 6, 9, 61, 19, 3, '2017-02-03 05:42:52', null);
insert into request (title, description, priority_status_id, progress_status_id, reporter_id, assignee_id, estimate_time_in_days, date_of_creation, joined_request_id) values ('amet lobortis sapien', 'aliquam quis turpis eget elit sodales scelerisque', 5, 11, 53, 40, 4, '2017-02-04 10:59:06', null);
insert into request (title, description, priority_status_id, progress_status_id, reporter_id, assignee_id, estimate_time_in_days, date_of_creation, joined_request_id) values ('posuere cubilia curae', 'quam pede lobortis ligula sit amet eleifend pede libero', 5, 8, 111, 17, 2, '2017-02-07 17:40:09', null);
insert into request (title, description, priority_status_id, progress_status_id, reporter_id, assignee_id, estimate_time_in_days, date_of_creation, joined_request_id) values ('lacus morbi quis', 'malesuada in imperdiet et commodo vulputate justo in blandit ultrices', 4, 9, 87, 19, 4, '2017-02-09 02:51:39', null);
insert into request (title, description, priority_status_id, progress_status_id, reporter_id, assignee_id, estimate_time_in_days, date_of_creation, joined_request_id) values ('in quam fringilla', 'vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis', 4, 10, 54, 43, 3, '2017-02-13 20:43:33', null);
insert into request (title, description, priority_status_id, progress_status_id, reporter_id, assignee_id, estimate_time_in_days, date_of_creation, joined_request_id) values ('platea dictumst etiam', 'sit amet justo morbi ut odio cras mi pede malesuada', 6, 10, 64, 34, 5, '2017-02-01 22:09:13', null);
insert into request (title, description, priority_status_id, progress_status_id, reporter_id, assignee_id, estimate_time_in_days, date_of_creation, joined_request_id) values ('non interdum in', 'nisl nunc rhoncus dui vel sem', 5, 7, 106, 25, 1, '2017-02-03 19:30:58', null);
insert into request (title, description, priority_status_id, progress_status_id, reporter_id, assignee_id, estimate_time_in_days, date_of_creation, joined_request_id) values ('diam erat fermentum', 'duis ac nibh fusce lacus purus aliquet at feugiat non', 4, 11, 102, 45, 6, '2017-02-11 11:08:50', null);
insert into request (title, description, priority_status_id, progress_status_id, reporter_id, assignee_id, estimate_time_in_days, date_of_creation, joined_request_id) values ('tristique est et', 'tincidunt eget tempus vel pede morbi porttitor lorem', 6, 10, 109, 31, 7, '2017-02-04 12:52:09', null);
insert into request (title, description, priority_status_id, progress_status_id, reporter_id, assignee_id, estimate_time_in_days, date_of_creation, joined_request_id) values ('pede ullamcorper augue', 'massa id nisl venenatis lacinia aenean sit', 4, 10, 98, 42, 5, '2017-02-15 08:16:40', null);
insert into request (title, description, priority_status_id, progress_status_id, reporter_id, assignee_id, estimate_time_in_days, date_of_creation, joined_request_id) values ('luctus et ultrices', 'suscipit nulla elit ac nulla sed', 5, 9, 66, 40, 5, '2017-02-14 23:52:56', null);
insert into request (title, description, priority_status_id, progress_status_id, reporter_id, assignee_id, estimate_time_in_days, date_of_creation, joined_request_id) values ('non interdum in', 'tincidunt nulla mollis molestie lorem quisque ut', 6, 10, 90, 25, 2, '2017-02-10 05:24:45', null);
insert into request (title, description, priority_status_id, progress_status_id, reporter_id, assignee_id, estimate_time_in_days, date_of_creation, joined_request_id) values ('maecenas pulvinar lobortis', 'luctus cum sociis natoque penatibus et magnis dis parturient montes', 5, 10, 78, 27, 4, '2017-02-14 19:14:24', null);
insert into request (title, description, priority_status_id, progress_status_id, reporter_id, assignee_id, estimate_time_in_days, date_of_creation, joined_request_id) values ('eget semper rutrum', 'dui nec nisi volutpat eleifend', 6, 12, 72, 39, 1, '2017-02-11 10:44:21', null);
insert into request (title, description, priority_status_id, progress_status_id, reporter_id, assignee_id, estimate_time_in_days, date_of_creation, joined_request_id) values ('dui nec nisi', 'at nunc commodo placerat praesent', 5, 11, 91, 22, 7, '2017-02-02 02:22:46', null);
insert into request (title, description, priority_status_id, progress_status_id, reporter_id, assignee_id, estimate_time_in_days, date_of_creation, joined_request_id) values ('tellus semper interdum', 'adipiscing elit proin interdum mauris non ligula pellentesque ultrices', 4, 12, 94, 46, 4, '2017-02-06 12:13:26', null);
insert into request (title, description, priority_status_id, progress_status_id, reporter_id, assignee_id, estimate_time_in_days, date_of_creation, joined_request_id) values ('nibh quisque id', 'natoque penatibus et magnis dis parturient montes', 4, 9, 67, 16, 4, '2017-02-05 14:21:23', null);
insert into request (title, description, priority_status_id, progress_status_id, reporter_id, assignee_id, estimate_time_in_days, date_of_creation, joined_request_id) values ('congue vivamus metus', 'tincidunt lacus at velit vivamus vel nulla eget eros', 5, 10, 75, 18, 5, '2017-02-14 11:57:56', null);
insert into request (title, description, priority_status_id, progress_status_id, reporter_id, assignee_id, estimate_time_in_days, date_of_creation, joined_request_id) values ('in hac habitasse', 'interdum mauris non ligula pellentesque ultrices phasellus id sapien in', 4, 7, 69, 44, 5, '2017-02-06 07:32:48', null);
insert into request (title, description, priority_status_id, progress_status_id, reporter_id, assignee_id, estimate_time_in_days, date_of_creation, joined_request_id) values ('volutpat erat quisque', 'luctus cum sociis natoque penatibus et magnis dis', 5, 10, 93, 52, 3, '2017-02-02 22:35:20', null);
insert into request (title, description, priority_status_id, progress_status_id, reporter_id, assignee_id, estimate_time_in_days, date_of_creation, joined_request_id) values ('fermentum donec ut', 'pellentesque at nulla suspendisse potenti cras in purus eu', 6, 9, 55, 17, 6, '2017-02-08 03:45:26', null);
insert into request (title, description, priority_status_id, progress_status_id, reporter_id, assignee_id, estimate_time_in_days, date_of_creation, joined_request_id) values ('amet consectetuer adipiscing', 'nulla sed accumsan felis ut at dolor quis odio', 6, 9, 66, 28, 3, '2017-02-19 11:48:26', null);
insert into request (title, description, priority_status_id, progress_status_id, reporter_id, assignee_id, estimate_time_in_days, date_of_creation, joined_request_id) values ('commodo placerat praesent', 'justo maecenas rhoncus aliquam lacus morbi quis tortor', 5, 9, 67, 28, 1, '2017-02-15 11:46:12', null);
insert into request (title, description, priority_status_id, progress_status_id, reporter_id, assignee_id, estimate_time_in_days, date_of_creation, joined_request_id) values ('in imperdiet et', 'pellentesque ultrices phasellus id sapien in sapien iaculis', 4, 7, 73, 51, 5, '2017-02-08 06:46:42', null);
insert into request (title, description, priority_status_id, progress_status_id, reporter_id, assignee_id, estimate_time_in_days, date_of_creation, joined_request_id) values ('nibh fusce lacus', 'in ante vestibulum ante ipsum primis', 6, 8, 110, 19, 3, '2017-02-10 17:50:09', null);
insert into request (title, description, priority_status_id, progress_status_id, reporter_id, assignee_id, estimate_time_in_days, date_of_creation, joined_request_id) values ('ligula vehicula consequat', 'nulla justo aliquam quis turpis eget elit sodales scelerisque mauris', 5, 7, 85, 43, 1, '2017-02-04 05:14:39', null);
insert into request (title, description, priority_status_id, progress_status_id, reporter_id, assignee_id, estimate_time_in_days, date_of_creation, joined_request_id) values ('massa id lobortis', 'sed accumsan felis ut at dolor', 6, 8, 92, 41, 6, '2017-02-13 20:20:52', null);
insert into request (title, description, priority_status_id, progress_status_id, reporter_id, assignee_id, estimate_time_in_days, date_of_creation, joined_request_id) values ('hac habitasse platea', 'lectus pellentesque eget nunc donec quis orci eget', 4, 7, 70, 49, 3, '2017-02-04 23:03:49', null);
insert into request (title, description, priority_status_id, progress_status_id, reporter_id, assignee_id, estimate_time_in_days, date_of_creation, joined_request_id) values ('eu est congue', 'donec posuere metus vitae ipsum aliquam non mauris morbi non', 4, 9, 57, 33, 7, '2017-02-04 16:57:10', null);
insert into request (title, description, priority_status_id, progress_status_id, reporter_id, assignee_id, estimate_time_in_days, date_of_creation, joined_request_id) values ('cum sociis natoque', 'dolor sit amet consectetuer adipiscing elit proin risus praesent', 6, 10, 91, 31, 7, '2017-02-03 05:21:00', null);
insert into request (title, description, priority_status_id, progress_status_id, reporter_id, assignee_id, estimate_time_in_days, date_of_creation, joined_request_id) values ('maecenas pulvinar lobortis', 'id nisl venenatis lacinia aenean sit amet justo morbi', 4, 11, 86, 43, 3, '2017-02-05 16:31:52', null);
insert into request (title, description, priority_status_id, progress_status_id, reporter_id, assignee_id, estimate_time_in_days, date_of_creation, joined_request_id) values ('mauris eget massa', 'ut nunc vestibulum ante ipsum primis in', 4, 10, 70, 24, 5, '2017-02-10 09:12:29', null);
insert into request (title, description, priority_status_id, progress_status_id, reporter_id, assignee_id, estimate_time_in_days, date_of_creation, joined_request_id) values ('nibh quisque id', 'morbi non lectus aliquam sit amet diam in magna', 4, 10, 77, 39, 6, '2017-02-09 19:21:24', null);
insert into request (title, description, priority_status_id, progress_status_id, reporter_id, assignee_id, estimate_time_in_days, date_of_creation, joined_request_id) values ('iaculis diam erat', 'ante ipsum primis in faucibus', 4, 7, 54, 34, 7, '2017-02-19 08:25:18', null);
insert into request (title, description, priority_status_id, progress_status_id, reporter_id, assignee_id, estimate_time_in_days, date_of_creation, joined_request_id) values ('in hac habitasse', 'vestibulum proin eu mi nulla ac', 5, 11, 62, 23, 7, '2017-02-01 21:49:33', null);
insert into request (title, description, priority_status_id, progress_status_id, reporter_id, assignee_id, estimate_time_in_days, date_of_creation, joined_request_id) values ('felis eu sapien', 'luctus nec molestie sed justo pellentesque viverra pede', 4, 8, 90, 48, 3, '2017-02-19 13:29:24', null);
insert into request (title, description, priority_status_id, progress_status_id, reporter_id, assignee_id, estimate_time_in_days, date_of_creation, joined_request_id) values ('rhoncus dui vel', 'justo etiam pretium iaculis justo in hac', 6, 11, 75, 48, 2, '2017-02-03 02:42:36', null);
insert into request (title, description, priority_status_id, progress_status_id, reporter_id, assignee_id, estimate_time_in_days, date_of_creation, joined_request_id) values ('ridiculus mus etiam', 'aliquam sit amet diam in', 5, 9, 107, 28, 3, '2017-02-14 05:09:21', null);
insert into request (title, description, priority_status_id, progress_status_id, reporter_id, assignee_id, estimate_time_in_days, date_of_creation, joined_request_id) values ('sed vel enim', 'curae nulla dapibus dolor vel est donec odio justo', 6, 7, 68, 37, 5, '2017-02-05 13:48:30', null);
insert into request (title, description, priority_status_id, progress_status_id, reporter_id, assignee_id, estimate_time_in_days, date_of_creation, joined_request_id) values ('vitae mattis nibh', 'quam a odio in hac habitasse', 6, 7, 89, 16, 1, '2017-02-02 02:36:22', null);
insert into request (title, description, priority_status_id, progress_status_id, reporter_id, assignee_id, estimate_time_in_days, date_of_creation, joined_request_id) values ('pellentesque ultrices phasellus', 'sit amet nulla quisque arcu libero rutrum ac lobortis', 5, 11, 69, 17, 6, '2017-02-01 04:42:25', null);
insert into request (title, description, priority_status_id, progress_status_id, reporter_id, assignee_id, estimate_time_in_days, date_of_creation, joined_request_id) values ('odio cras mi', 'leo rhoncus sed vestibulum sit amet', 5, 10, 53, 31, 5, '2017-02-12 06:30:55', null);
insert into request (title, description, priority_status_id, progress_status_id, reporter_id, assignee_id, estimate_time_in_days, date_of_creation, joined_request_id) values ('ultrices posuere cubilia', 'odio consequat varius integer ac leo pellentesque ultrices mattis odio', 5, 7, 85, 35, 2, '2017-02-14 11:04:46', null);
insert into request (title, description, priority_status_id, progress_status_id, reporter_id, assignee_id, estimate_time_in_days, date_of_creation, joined_request_id) values ('in faucibus orci', 'tellus semper interdum mauris ullamcorper purus', 5, 12, 72, 29, 6, '2017-02-17 08:31:18', null);
insert into request (title, description, priority_status_id, progress_status_id, reporter_id, assignee_id, estimate_time_in_days, date_of_creation, joined_request_id) values ('a ipsum integer', 'sagittis nam congue risus semper porta', 6, 10, 65, 50, 4, '2017-02-19 03:57:25', null);
insert into request (title, description, priority_status_id, progress_status_id, reporter_id, assignee_id, estimate_time_in_days, date_of_creation, joined_request_id) values ('vel augue vestibulum', 'cubilia curae donec pharetra magna vestibulum aliquet', 5, 10, 93, 32, 5, '2017-02-01 02:59:13', null);
insert into request (title, description, priority_status_id, progress_status_id, reporter_id, assignee_id, estimate_time_in_days, date_of_creation, joined_request_id) values ('porta volutpat erat', 'ac lobortis vel dapibus at', 4, 9, 68, 32, 4, '2017-02-05 14:45:40', null);
insert into request (title, description, priority_status_id, progress_status_id, reporter_id, assignee_id, estimate_time_in_days, date_of_creation, joined_request_id) values ('nec dui luctus', 'lobortis vel dapibus at diam nam tristique tortor eu pede', 4, 9, 111, 48, 5, '2017-02-05 08:30:47', null);
insert into request (title, description, priority_status_id, progress_status_id, reporter_id, assignee_id, estimate_time_in_days, date_of_creation, joined_request_id) values ('diam erat fermentum', 'tincidunt nulla mollis molestie lorem quisque ut erat', 4, 11, 97, 24, 2, '2017-02-13 12:20:22', null);
insert into request (title, description, priority_status_id, progress_status_id, reporter_id, assignee_id, estimate_time_in_days, date_of_creation, joined_request_id) values ('vestibulum velit id', 'duis consequat dui nec nisi', 5, 12, 61, 17, 5, '2017-02-08 07:56:46', null);
insert into request (title, description, priority_status_id, progress_status_id, reporter_id, assignee_id, estimate_time_in_days, date_of_creation, joined_request_id) values ('erat nulla tempus', 'ut volutpat sapien arcu sed augue aliquam erat volutpat in', 5, 8, 103, 52, 1, '2017-02-14 23:07:30', null);
insert into request (title, description, priority_status_id, progress_status_id, reporter_id, assignee_id, estimate_time_in_days, date_of_creation, joined_request_id) values ('turpis adipiscing lorem', 'quis orci eget orci vehicula condimentum curabitur', 6, 10, 84, 49, 5, '2017-02-01 10:02:22', null);
insert into request (title, description, priority_status_id, progress_status_id, reporter_id, assignee_id, estimate_time_in_days, date_of_creation, joined_request_id) values ('pretium nisl ut', 'nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus', 6, 12, 92, 26, 3, '2017-02-16 11:19:27', null);
insert into request (title, description, priority_status_id, progress_status_id, reporter_id, assignee_id, estimate_time_in_days, date_of_creation, joined_request_id) values ('quisque porta volutpat', 'penatibus et magnis dis parturient', 5, 8, 78, 50, 1, '2017-02-05 18:20:14', null);
insert into request (title, description, priority_status_id, progress_status_id, reporter_id, assignee_id, estimate_time_in_days, date_of_creation, joined_request_id) values ('ultrices erat tortor', 'ante vivamus tortor duis mattis egestas metus aenean', 6, 11, 89, 44, 5, '2017-02-19 19:21:19', null);
insert into request (title, description, priority_status_id, progress_status_id, reporter_id, assignee_id, estimate_time_in_days, date_of_creation, joined_request_id) values ('porttitor id consequat', 'magna vulputate luctus cum sociis natoque penatibus et magnis', 4, 7, 56, 28, 3, '2017-02-01 08:15:37', null);
insert into request (title, description, priority_status_id, progress_status_id, reporter_id, assignee_id, estimate_time_in_days, date_of_creation, joined_request_id) values ('mus vivamus vestibulum', 'odio porttitor id consequat in', 6, 9, 106, 50, 4, '2017-02-13 20:14:59', null);
insert into request (title, description, priority_status_id, progress_status_id, reporter_id, assignee_id, estimate_time_in_days, date_of_creation, joined_request_id) values ('suspendisse ornare consequat', 'purus sit amet nulla quisque arcu libero rutrum', 6, 7, 110, 21, 5, '2017-02-14 11:17:07', null);
insert into request (title, description, priority_status_id, progress_status_id, reporter_id, assignee_id, estimate_time_in_days, date_of_creation, joined_request_id) values ('elementum ligula vehicula', 'quisque porta volutpat erat quisque erat eros viverra eget congue', 5, 9, 69, 50, 2, '2017-02-07 02:29:11', null);
insert into request (title, description, priority_status_id, progress_status_id, reporter_id, assignee_id, estimate_time_in_days, date_of_creation, joined_request_id) values ('felis sed interdum', 'cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat', 5, 10, 75, 40, 2, '2017-02-11 13:45:12', null);
insert into request (title, description, priority_status_id, progress_status_id, reporter_id, assignee_id, estimate_time_in_days, date_of_creation, joined_request_id) values ('nascetur ridiculus mus', 'erat fermentum justo nec condimentum neque sapien', 5, 9, 89, 26, 4, '2017-02-10 06:50:04', null);
insert into request (title, description, priority_status_id, progress_status_id, reporter_id, assignee_id, estimate_time_in_days, date_of_creation, joined_request_id) values ('aliquam quis turpis', 'justo eu massa donec dapibus duis at velit eu', 6, 11, 109, 48, 6, '2017-02-03 23:22:53', null);
insert into request (title, description, priority_status_id, progress_status_id, reporter_id, assignee_id, estimate_time_in_days, date_of_creation, joined_request_id) values ('ipsum primis in', 'orci luctus et ultrices posuere', 4, 9, 89, 41, 5, '2017-02-02 15:43:01', null);
insert into request (title, description, priority_status_id, progress_status_id, reporter_id, assignee_id, estimate_time_in_days, date_of_creation, joined_request_id) values ('pellentesque ultrices mattis', 'sed vel enim sit amet nunc viverra dapibus nulla suscipit', 6, 9, 105, 26, 7, '2017-02-18 21:27:27', null);
insert into request (title, description, priority_status_id, progress_status_id, reporter_id, assignee_id, estimate_time_in_days, date_of_creation, joined_request_id) values ('quam pede lobortis', 'porta volutpat erat quisque erat', 5, 10, 69, 43, 4, '2017-02-03 20:38:05', null);
insert into request (title, description, priority_status_id, progress_status_id, reporter_id, assignee_id, estimate_time_in_days, date_of_creation, joined_request_id) values ('purus sit amet', 'penatibus et magnis dis parturient montes nascetur ridiculus', 5, 7, 84, 36, 7, '2017-02-14 15:02:33', null);
insert into request (title, description, priority_status_id, progress_status_id, reporter_id, assignee_id, estimate_time_in_days, date_of_creation, joined_request_id) values ('dui nec nisi', 'nisi eu orci mauris lacinia', 5, 9, 100, 48, 2, '2017-02-05 22:44:11', null);
insert into request (title, description, priority_status_id, progress_status_id, reporter_id, assignee_id, estimate_time_in_days, date_of_creation, joined_request_id) values ('in hac habitasse', 'vestibulum sagittis sapien cum sociis', 6, 12, 71, 46, 2, '2017-02-05 14:55:14', null);
insert into request (title, description, priority_status_id, progress_status_id, reporter_id, assignee_id, estimate_time_in_days, date_of_creation, joined_request_id) values ('quisque arcu libero', 'in felis donec semper sapien', 6, 8, 97, 43, 7, '2017-02-11 18:28:04', null);
insert into request (title, description, priority_status_id, progress_status_id, reporter_id, assignee_id, estimate_time_in_days, date_of_creation, joined_request_id) values ('dui proin leo', 'praesent lectus vestibulum quam sapien varius ut blandit non', 4, 9, 67, 27, 7, '2017-02-09 09:36:52', null);
insert into request (title, description, priority_status_id, progress_status_id, reporter_id, assignee_id, estimate_time_in_days, date_of_creation, joined_request_id) values ('eu est congue', 'eu est congue elementum in', 6, 11, 100, 22, 3, '2017-02-07 04:51:51', null);
insert into request (title, description, priority_status_id, progress_status_id, reporter_id, assignee_id, estimate_time_in_days, date_of_creation, joined_request_id) values ('in lectus pellentesque', 'nulla mollis molestie lorem quisque', 6, 7, 62, 27, 5, '2017-02-17 01:59:16', null);

insert into sub_request (title, description, request_id) values ('arcu sed augue', 'nisl ut volutpat sapien arcu', 113);
insert into sub_request (title, description, request_id) values ('non pretium', 'consequat varius integer ac leo pellentesque ultrices mattis odio', 113);
insert into sub_request (title, description, request_id) values ('vulputate ut', 'curabitur gravida nisi at nibh in hac habitasse', 113);
insert into sub_request (title, description, request_id) values ('id massa id', 'condimentum neque sapien placerat ante nulla justo aliquam quis', 113);
insert into sub_request (title, description, request_id) values ('pulvinar nulla pede', 'praesent blandit nam nulla integer pede justo lacinia', 114);
insert into sub_request (title, description, request_id) values ('primis in', 'nisl duis ac nibh fusce lacus purus aliquet', 114);
insert into sub_request (title, description, request_id) values ('proin risus praesent', 'aliquet pulvinar sed nisl nunc rhoncus dui', 114);
insert into sub_request (title, description, request_id) values ('purus eu', 'a feugiat et eros vestibulum ac est lacinia nisi', 115);
insert into sub_request (title, description, request_id) values ('lorem integer', 'eget orci vehicula condimentum curabitur in libero', 115);
insert into sub_request (title, description, request_id) values ('dictumst morbi', 'adipiscing elit proin risus praesent lectus vestibulum', 116);
insert into sub_request (title, description, request_id) values ('at vulputate', 'rutrum nulla nunc purus phasellus in', 116);
insert into sub_request (title, description, request_id) values ('odio porttitor', 'praesent id massa id nisl venenatis lacinia', 116);
insert into sub_request (title, description, request_id) values ('pharetra magna vestibulum', 'turpis enim blandit mi in', 116);
insert into sub_request (title, description, request_id) values ('mauris lacinia', 'lectus suspendisse potenti in eleifend quam', 117);
insert into sub_request (title, description, request_id) values ('tincidunt in leo', 'amet consectetuer adipiscing elit proin interdum mauris non ligula', 117);
insert into sub_request (title, description, request_id) values ('eleifend donec ut', 'blandit non interdum in ante vestibulum ante ipsum primis in', 117);
insert into sub_request (title, description, request_id) values ('eget nunc donec', 'nunc commodo placerat praesent blandit nam nulla integer', 117);
insert into sub_request (title, description, request_id) values ('sapien placerat', 'fusce lacus purus aliquet at', 117);
insert into sub_request (title, description, request_id) values ('blandit lacinia', 'placerat ante nulla justo aliquam quis turpis', 118);
insert into sub_request (title, description, request_id) values ('vel est donec', 'massa quis augue luctus tincidunt', 118);
insert into sub_request (title, description, request_id) values ('quis orci eget', 'posuere nonummy integer non velit', 119);
insert into sub_request (title, description, request_id) values ('faucibus cursus urna', 'adipiscing elit proin risus praesent lectus vestibulum quam sapien varius', 119);
insert into sub_request (title, description, request_id) values ('aenean fermentum', 'eget nunc donec quis orci eget orci', 119);
insert into sub_request (title, description, request_id) values ('in sagittis', 'ipsum ac tellus semper interdum mauris', 119);
insert into sub_request (title, description, request_id) values ('pharetra magna', 'eu massa donec dapibus duis at', 120);
insert into sub_request (title, description, request_id) values ('magna vulputate', 'volutpat in congue etiam justo etiam pretium iaculis justo', 120);
insert into sub_request (title, description, request_id) values ('nunc proin', 'a pede posuere nonummy integer non', 120);
insert into sub_request (title, description, request_id) values ('morbi non', 'viverra pede ac diam cras pellentesque volutpat dui maecenas', 120);
insert into sub_request (title, description, request_id) values ('massa quis', 'mi in porttitor pede justo eu massa donec dapibus duis', 121);
insert into sub_request (title, description, request_id) values ('vivamus vestibulum', 'convallis morbi odio odio elementum eu interdum eu tincidunt in', 121);
insert into sub_request (title, description, request_id) values ('nascetur ridiculus', 'donec diam neque vestibulum eget', 121);
insert into sub_request (title, description, request_id) values ('lorem quisque ut', 'in faucibus orci luctus et ultrices posuere', 121);
insert into sub_request (title, description, request_id) values ('ante ipsum', 'turpis sed ante vivamus tortor duis mattis egestas metus aenean', 122);
insert into sub_request (title, description, request_id) values ('varius integer', 'justo in blandit ultrices enim lorem ipsum dolor', 122);
insert into sub_request (title, description, request_id) values ('magna vestibulum aliquet', 'et ultrices posuere cubilia curae mauris viverra diam', 123);
insert into sub_request (title, description, request_id) values ('quis tortor', 'pede libero quis orci nullam molestie nibh in', 123);
insert into sub_request (title, description, request_id) values ('dictumst aliquam', 'mauris eget massa tempor convallis nulla neque', 123);
insert into sub_request (title, description, request_id) values ('augue vestibulum', 'risus praesent lectus vestibulum quam sapien varius ut blandit non', 123);
insert into sub_request (title, description, request_id) values ('imperdiet nullam orci', 'at nibh in hac habitasse platea dictumst aliquam augue quam', 124);
insert into sub_request (title, description, request_id) values ('accumsan tortor', 'est congue elementum in hac habitasse platea', 124);
insert into sub_request (title, description, request_id) values ('amet eleifend', 'orci pede venenatis non sodales sed tincidunt eu felis fusce', 125);
insert into sub_request (title, description, request_id) values ('id nulla', 'montes nascetur ridiculus mus etiam vel augue', 125);
insert into sub_request (title, description, request_id) values ('nec sem', 'molestie hendrerit at vulputate vitae nisl aenean', 125);
insert into sub_request (title, description, request_id) values ('imperdiet nullam orci', 'mattis egestas metus aenean fermentum donec ut mauris eget', 126);
insert into sub_request (title, description, request_id) values ('convallis eget eleifend', 'imperdiet et commodo vulputate justo in blandit ultrices enim', 126);
insert into sub_request (title, description, request_id) values ('amet erat nulla', 'maecenas leo odio condimentum id luctus', 127);
insert into sub_request (title, description, request_id) values ('pede ullamcorper', 'vestibulum ante ipsum primis in faucibus', 127);
insert into sub_request (title, description, request_id) values ('amet lobortis', 'augue luctus tincidunt nulla mollis molestie lorem', 127);
insert into sub_request (title, description, request_id) values ('curabitur gravida', 'enim leo rhoncus sed vestibulum sit', 128);
insert into sub_request (title, description, request_id) values ('nisl venenatis lacinia', 'dis parturient montes nascetur ridiculus mus etiam vel augue', 128);
insert into sub_request (title, description, request_id) values ('placerat ante nulla', 'ac nibh fusce lacus purus aliquet', 129);
insert into sub_request (title, description, request_id) values ('eu pede', 'vivamus vestibulum sagittis sapien cum', 129);
insert into sub_request (title, description, request_id) values ('tristique fusce congue', 'amet eros suspendisse accumsan tortor quis turpis sed', 129);
insert into sub_request (title, description, request_id) values ('sit amet consectetuer', 'suspendisse potenti nullam porttitor lacus at', 130);
insert into sub_request (title, description, request_id) values ('sed tincidunt eu', 'quis orci eget orci vehicula condimentum curabitur in libero', 130);
insert into sub_request (title, description, request_id) values ('diam id', 'penatibus et magnis dis parturient montes nascetur', 131);
insert into sub_request (title, description, request_id) values ('vel est', 'ante ipsum primis in faucibus orci luctus et ultrices', 131);
insert into sub_request (title, description, request_id) values ('nec condimentum', 'malesuada in imperdiet et commodo vulputate justo in blandit', 131);
insert into sub_request (title, description, request_id) values ('magna vulputate', 'mi nulla ac enim in tempor turpis', 132);
insert into sub_request (title, description, request_id) values ('at velit', 'amet nunc viverra dapibus nulla suscipit ligula in', 132);
insert into sub_request (title, description, request_id) values ('nullam sit', 'montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis', 133);
insert into sub_request (title, description, request_id) values ('pede morbi', 'eget tincidunt eget tempus vel pede morbi porttitor lorem id', 133);
insert into sub_request (title, description, request_id) values ('lacus curabitur', 'praesent lectus vestibulum quam sapien varius', 133);
insert into sub_request (title, description, request_id) values ('ut erat', 'felis eu sapien cursus vestibulum proin eu mi', 133);
insert into sub_request (title, description, request_id) values ('cursus urna', 'potenti in eleifend quam a odio', 134);
insert into sub_request (title, description, request_id) values ('mus etiam', 'integer non velit donec diam neque vestibulum eget vulputate', 134);
insert into sub_request (title, description, request_id) values ('tortor sollicitudin', 'risus auctor sed tristique in tempus sit amet sem', 135);
insert into sub_request (title, description, request_id) values ('nam dui proin', 'ultrices aliquet maecenas leo odio condimentum id luctus nec molestie', 135);
insert into sub_request (title, description, request_id) values ('sit amet', 'mauris laoreet ut rhoncus aliquet pulvinar sed', 135);
insert into sub_request (title, description, request_id) values ('quis justo', 'pulvinar sed nisl nunc rhoncus dui vel sem', 136);
insert into sub_request (title, description, request_id) values ('platea dictumst aliquam', 'ut suscipit a feugiat et eros vestibulum ac est', 136);
insert into sub_request (title, description, request_id) values ('eget elit sodales', 'sed sagittis nam congue risus semper porta volutpat', 136);
insert into sub_request (title, description, request_id) values ('consectetuer adipiscing', 'massa donec dapibus duis at velit', 137);
insert into sub_request (title, description, request_id) values ('elementum ligula', 'ornare imperdiet sapien urna pretium nisl ut volutpat sapien', 137);
insert into sub_request (title, description, request_id) values ('libero rutrum', 'in hac habitasse platea dictumst maecenas ut massa quis', 138);
insert into sub_request (title, description, request_id) values ('morbi ut', 'montes nascetur ridiculus mus etiam vel augue vestibulum', 138);
insert into sub_request (title, description, request_id) values ('id justo sit', 'aliquam lacus morbi quis tortor id nulla ultrices', 138);
insert into sub_request (title, description, request_id) values ('libero rutrum ac', 'turpis a pede posuere nonummy integer non velit donec', 139);
insert into sub_request (title, description, request_id) values ('vehicula consequat morbi', 'sem sed sagittis nam congue risus semper', 139);
insert into sub_request (title, description, request_id) values ('nascetur ridiculus', 'interdum venenatis turpis enim blandit mi', 140);
insert into sub_request (title, description, request_id) values ('consequat ut', 'nisl ut volutpat sapien arcu', 140);
insert into sub_request (title, description, request_id) values ('ipsum integer', 'praesent blandit lacinia erat vestibulum', 141);
insert into sub_request (title, description, request_id) values ('sollicitudin mi', 'fusce consequat nulla nisl nunc nisl', 141);
insert into sub_request (title, description, request_id) values ('diam in magna', 'cras pellentesque volutpat dui maecenas tristique est et tempus semper', 142);
insert into sub_request (title, description, request_id) values ('tristique est', 'at feugiat non pretium quis lectus suspendisse potenti in eleifend', 142);
insert into sub_request (title, description, request_id) values ('augue vel accumsan', 'vel lectus in quam fringilla rhoncus mauris enim leo', 142);
insert into sub_request (title, description, request_id) values ('ut nulla', 'ipsum dolor sit amet consectetuer', 143);
insert into sub_request (title, description, request_id) values ('nam congue risus', 'eu magna vulputate luctus cum sociis natoque penatibus et', 143);
insert into sub_request (title, description, request_id) values ('vestibulum ante ipsum', 'aenean auctor gravida sem praesent id', 143);
insert into sub_request (title, description, request_id) values ('nonummy maecenas tincidunt', 'rutrum at lorem integer tincidunt ante', 144);
insert into sub_request (title, description, request_id) values ('sit amet consectetuer', 'lacus at turpis donec posuere metus vitae', 144);
insert into sub_request (title, description, request_id) values ('luctus ultricies', 'condimentum id luctus nec molestie sed justo pellentesque viverra', 145);
insert into sub_request (title, description, request_id) values ('vestibulum vestibulum', 'vel sem sed sagittis nam congue risus semper', 145);
insert into sub_request (title, description, request_id) values ('interdum in', 'posuere felis sed lacus morbi sem', 146);
insert into sub_request (title, description, request_id) values ('velit eu', 'donec posuere metus vitae ipsum aliquam non', 146);
insert into sub_request (title, description, request_id) values ('libero non mattis', 'vestibulum ante ipsum primis in faucibus orci luctus et', 147);
insert into sub_request (title, description, request_id) values ('amet consectetuer adipiscing', 'dictumst etiam faucibus cursus urna ut tellus nulla', 147);
insert into sub_request (title, description, request_id) values ('non mauris', 'justo in hac habitasse platea dictumst etiam faucibus cursus urna', 147);
insert into sub_request (title, description, request_id) values ('morbi non lectus', 'justo nec condimentum neque sapien placerat', 148);
insert into sub_request (title, description, request_id) values ('arcu adipiscing molestie', 'faucibus accumsan odio curabitur convallis duis consequat dui nec nisi', 148);

insert into joined_request (title, description, assignee_id, priority_status_id, progress_status_id) values ('massa quis augue', 'at dolor quis odio consequat', 44, 4, 12);
insert into joined_request (title, description, assignee_id, priority_status_id, progress_status_id) values ('nulla suspendisse', 'nisl venenatis lacinia aenean sit', 48, 5, 12);
insert into joined_request (title, description, assignee_id, priority_status_id, progress_status_id) values ('consectetuer adipiscing', 'consequat ut nulla sed', 46, 4, 11);
insert into joined_request (title, description, assignee_id, priority_status_id, progress_status_id) values ('nulla eget', 'fusce congue diam id ornare imperdiet sapien', 17, 4, 12);
insert into joined_request (title, description, assignee_id, priority_status_id, progress_status_id) values ('sem mauris laoreet', 'neque sapien placerat ante nulla justo', 51, 6, 8);

UPDATE request SET joined_request_id = 313 WHERE id = 113;
UPDATE request SET joined_request_id = 313 WHERE id = 114;
UPDATE request SET joined_request_id = 313 WHERE id = 115;

UPDATE request SET joined_request_id = 314 WHERE id = 116;
UPDATE request SET joined_request_id = 314 WHERE id = 117;
UPDATE request SET joined_request_id = 314 WHERE id = 118;
UPDATE request SET joined_request_id = 314 WHERE id = 119;

UPDATE request SET joined_request_id = 315 WHERE id = 120;
UPDATE request SET joined_request_id = 315 WHERE id = 121;
UPDATE request SET joined_request_id = 315 WHERE id = 122;
UPDATE request SET joined_request_id = 315 WHERE id = 123;
UPDATE request SET joined_request_id = 315 WHERE id = 124;

UPDATE request SET joined_request_id = 316 WHERE id = 125;
UPDATE request SET joined_request_id = 316 WHERE id = 126;

UPDATE request SET joined_request_id = 317 WHERE id = 127;
UPDATE request SET joined_request_id = 317 WHERE id = 128;
UPDATE request SET joined_request_id = 317 WHERE id = 129;

insert into forum(title) values ('Employees forum');
insert into forum(title) values ('Office managers forum');

insert into topic (title, forum_id) values ('mattis odio', 318);
insert into topic (title, forum_id) values ('a suscipit', 318);
insert into topic (title, forum_id) values ('rutrum neque', 318);
insert into topic (title, forum_id) values ('sit amet', 318);
insert into topic (title, forum_id) values ('nulla sed', 318);
insert into topic (title, forum_id) values ('in felis', 318);
insert into topic (title, forum_id) values ('odio odio', 318);
insert into topic (title, forum_id) values ('ac enim', 318);
insert into topic (title, forum_id) values ('vel ipsum', 318);
insert into topic (title, forum_id) values ('adipiscing lorem', 318);
insert into topic (title, forum_id) values ('quis orci', 319);
insert into topic (title, forum_id) values ('id ligula', 319);
insert into topic (title, forum_id) values ('ante vestibulum', 319);
insert into topic (title, forum_id) values ('rhoncus aliquam', 319);
insert into topic (title, forum_id) values ('ullamcorper purus', 319);
insert into topic (title, forum_id) values ('et ultrices', 319);
insert into topic (title, forum_id) values ('volutpat in', 319);
insert into topic (title, forum_id) values ('at velit', 319);
insert into topic (title, forum_id) values ('ac consequat', 319);
insert into topic (title, forum_id) values ('ante ipsum', 319);

insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (16, 53, null, 'sit amet eros suspendisse accumsan tortor quis turpis sed', '2017-01-31 00:48:50');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (16, 53, null, 'morbi ut odio cras mi pede malesuada in', '2017-01-17 10:21:28');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (16, 53, null, 'nam nulla integer pede justo', '2017-01-08 06:52:12');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (16, 53, null, 'sapien arcu sed augue aliquam erat volutpat in congue etiam', '2017-01-07 11:30:14');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (16, 53, null, 'donec pharetra magna vestibulum aliquet', '2017-01-21 14:44:00');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (16, 53, null, 'nibh in quis justo maecenas rhoncus aliquam', '2017-01-18 16:42:52');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (16, 53, null, 'odio consequat varius integer ac', '2017-01-09 03:05:53');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (16, 53, null, 'enim in tempor turpis nec euismod scelerisque', '2017-01-11 19:16:42');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (16, 53, null, 'augue vestibulum ante ipsum primis in', '2017-01-29 14:09:11');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (16, 53, null, 'eget semper rutrum nulla nunc purus phasellus in felis', '2017-01-02 02:01:45');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (16, 53, null, 'congue diam id ornare imperdiet sapien', '2017-01-03 19:00:36');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (16, 53, null, 'rutrum rutrum neque aenean auctor gravida sem', '2017-01-13 15:16:17');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (16, 53, null, 'faucibus accumsan odio curabitur convallis duis consequat dui nec nisi', '2017-01-17 22:56:13');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (16, 53, null, 'commodo placerat praesent blandit nam nulla integer', '2017-01-01 14:26:18');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (16, 53, null, 'sapien placerat ante nulla justo aliquam quis turpis eget', '2017-01-16 00:53:57');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (16, 53, null, 'rhoncus aliquet pulvinar sed nisl nunc', '2017-01-07 05:28:36');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (16, 53, null, 'id ornare imperdiet sapien urna pretium nisl ut volutpat sapien', '2017-01-12 02:12:30');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (16, 53, null, 'non pretium quis lectus suspendisse', '2017-01-01 08:19:56');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (16, 53, null, 'dapibus augue vel accumsan tellus nisi eu', '2017-01-27 08:31:55');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (16, 53, null, 'aliquam non mauris morbi non lectus aliquam sit amet diam', '2017-01-22 17:23:04');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (16, 53, null, 'sapien dignissim vestibulum vestibulum ante', '2017-01-30 14:05:43');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (16, 53, null, 'adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus', '2017-01-04 17:30:24');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (16, 53, null, 'id mauris vulputate elementum nullam varius nulla facilisi cras non', '2017-01-17 10:56:57');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (16, 53, null, 'quisque erat eros viverra eget congue eget semper', '2017-01-30 04:41:00');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (16, 53, null, 'vel pede morbi porttitor lorem id ligula suspendisse', '2017-01-26 18:51:15');

insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (53, 16, null, 'mus vivamus vestibulum sagittis sapien cum sociis', '2017-01-11 04:37:27');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (53, 16, null, 'ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices', '2017-01-01 21:53:42');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (53, 16, null, 'felis eu sapien cursus vestibulum proin eu mi nulla ac', '2017-01-08 13:44:32');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (53, 16, null, 'vivamus vel nulla eget eros elementum pellentesque quisque', '2017-01-06 08:20:48');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (53, 16, null, 'duis faucibus accumsan odio curabitur convallis duis consequat', '2017-01-22 23:57:30');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (53, 16, null, 'lacinia sapien quis libero nullam sit amet turpis elementum', '2017-01-14 16:36:44');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (53, 16, null, 'mattis egestas metus aenean fermentum', '2017-01-31 05:52:37');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (53, 16, null, 'blandit non interdum in ante vestibulum ante ipsum primis', '2017-01-17 23:04:12');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (53, 16, null, 'vel accumsan tellus nisi eu', '2017-01-05 02:33:51');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (53, 16, null, 'lacinia eget tincidunt eget tempus vel pede morbi', '2017-01-21 01:59:18');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (53, 16, null, 'quis justo maecenas rhoncus aliquam lacus morbi quis tortor', '2017-01-21 03:15:03');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (53, 16, null, 'sit amet sem fusce consequat', '2017-01-21 21:37:17');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (53, 16, null, 'iaculis congue vivamus metus arcu', '2017-01-23 21:29:06');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (53, 16, null, 'orci eget orci vehicula condimentum curabitur', '2017-01-28 13:16:36');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (53, 16, null, 'vivamus vestibulum sagittis sapien cum sociis natoque penatibus', '2017-01-11 05:22:57');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (53, 16, null, 'nunc rhoncus dui vel sem sed sagittis nam congue', '2017-01-22 09:43:24');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (53, 16, null, 'turpis sed ante vivamus tortor duis mattis', '2017-01-19 13:46:23');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (53, 16, null, 'eget rutrum at lorem integer tincidunt ante vel', '2017-01-02 16:09:23');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (53, 16, null, 'condimentum id luctus nec molestie sed', '2017-01-15 06:36:47');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (53, 16, null, 'amet sapien dignissim vestibulum vestibulum ante', '2017-01-31 06:31:59');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (53, 16, null, 'lorem id ligula suspendisse ornare consequat', '2017-01-02 19:50:13');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (53, 16, null, 'convallis duis consequat dui nec nisi volutpat eleifend donec', '2017-01-30 20:24:04');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (53, 16, null, 'curabitur gravida nisi at nibh in hac habitasse platea', '2017-01-10 08:04:52');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (53, 16, null, 'amet sapien dignissim vestibulum vestibulum ante', '2017-01-24 07:31:41');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (53, 16, null, 'blandit non interdum in ante vestibulum ante ipsum', '2017-01-06 20:00:07');

insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (53, null, 337, 'suspendisse ornare consequat lectus in est risus auctor sed', '2017-01-18 09:25:59');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (17, null, 335, 'pede venenatis non sodales sed tincidunt eu felis fusce posuere', '2017-01-19 14:00:31');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (53, null, 334, 'nibh in hac habitasse platea dictumst aliquam augue', '2017-01-07 09:03:47');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (16, null, 331, 'ac tellus semper interdum mauris', '2017-01-12 16:04:16');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (53, null, 326, 'elementum eu interdum eu tincidunt in leo maecenas', '2017-01-02 20:13:00');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (13, null, 338, 'non velit donec diam neque vestibulum eget vulputate', '2017-01-20 20:39:18');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (16, null, 335, 'ridiculus mus etiam vel augue vestibulum', '2017-01-04 01:19:03');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (16, null, 324, 'dis parturient montes nascetur ridiculus', '2017-01-04 07:14:50');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (54, null, 330, 'interdum mauris non ligula pellentesque ultrices phasellus', '2017-01-29 07:01:42');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (54, null, 325, 'lectus pellentesque eget nunc donec quis orci eget orci vehicula', '2017-01-30 11:09:04');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (55, null, 329, 'ante ipsum primis in faucibus orci luctus', '2017-01-17 10:50:26');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (54, null, 320, 'eget tempus vel pede morbi porttitor lorem', '2017-01-01 02:08:42');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (53, null, 333, 'orci pede venenatis non sodales sed', '2017-01-24 06:01:11');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (54, null, 324, 'dui luctus rutrum nulla tellus in sagittis', '2017-01-09 15:36:20');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (17, null, 337, 'ut erat id mauris vulputate elementum', '2017-01-25 01:25:27');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (53, null, 337, 'ut dolor morbi vel lectus', '2017-01-24 08:59:20');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (16, null, 329, 'curae mauris viverra diam vitae quam suspendisse', '2017-01-30 21:50:58');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (54, null, 324, 'rhoncus aliquet pulvinar sed nisl nunc rhoncus', '2017-01-16 07:39:05');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (54, null, 333, 'vivamus in felis eu sapien cursus', '2017-01-22 01:31:00');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (13, null, 323, 'velit donec diam neque vestibulum eget vulputate', '2017-01-27 06:18:10');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (17, null, 322, 'suspendisse ornare consequat lectus in est', '2017-01-13 17:56:41');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (17, null, 337, 'leo rhoncus sed vestibulum sit amet', '2017-01-02 15:50:10');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (16, null, 322, 'aliquam lacus morbi quis tortor id', '2017-01-22 07:58:24');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (13, null, 320, 'suscipit nulla elit ac nulla', '2017-01-31 21:01:06');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (17, null, 339, 'etiam faucibus cursus urna ut', '2017-01-04 02:53:42');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (53, null, 330, 'donec ut mauris eget massa', '2017-01-11 12:41:11');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (53, null, 320, 'lacus at velit vivamus vel nulla eget', '2017-01-23 15:28:59');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (17, null, 327, 'et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum', '2017-01-31 14:09:34');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (17, null, 338, 'id turpis integer aliquet massa id lobortis convallis', '2017-01-07 09:11:39');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (16, null, 336, 'quis odio consequat varius integer', '2017-01-05 15:58:55');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (54, null, 321, 'nisl duis bibendum felis sed interdum venenatis turpis enim blandit', '2017-01-13 06:58:07');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (54, null, 321, 'etiam vel augue vestibulum rutrum rutrum neque aenean', '2017-01-17 11:12:23');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (53, null, 327, 'venenatis turpis enim blandit mi in', '2017-01-06 03:36:46');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (54, null, 336, 'libero nullam sit amet turpis elementum ligula vehicula consequat morbi', '2017-01-31 10:07:43');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (13, null, 328, 'nulla sed vel enim sit amet nunc viverra dapibus', '2017-01-23 14:29:55');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (55, null, 335, 'etiam pretium iaculis justo in', '2017-01-07 13:27:51');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (13, null, 335, 'potenti cras in purus eu magna', '2017-01-13 11:50:13');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (55, null, 334, 'praesent id massa id nisl venenatis lacinia aenean', '2017-01-09 23:58:00');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (53, null, 332, 'praesent id massa id nisl venenatis lacinia', '2017-01-20 05:12:53');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (53, null, 337, 'nibh fusce lacus purus aliquet at feugiat non pretium', '2017-01-11 09:48:43');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (18, null, 327, 'rhoncus aliquet pulvinar sed nisl', '2017-01-09 05:44:09');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (54, null, 329, 'aliquet maecenas leo odio condimentum', '2017-01-23 23:05:55');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (13, null, 323, 'aliquam convallis nunc proin at turpis a pede posuere nonummy', '2017-01-01 07:20:40');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (17, null, 324, 'odio in hac habitasse platea', '2017-01-21 22:25:03');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (18, null, 332, 'augue vestibulum ante ipsum primis in faucibus orci luctus', '2017-01-20 05:01:48');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (18, null, 325, 'blandit nam nulla integer pede', '2017-01-18 04:01:09');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (17, null, 321, 'elit sodales scelerisque mauris sit amet eros suspendisse accumsan tortor', '2017-01-09 12:53:45');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (54, null, 327, 'convallis tortor risus dapibus augue vel accumsan', '2017-01-01 04:28:54');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (54, null, 331, 'amet consectetuer adipiscing elit proin interdum mauris non ligula', '2017-01-07 13:15:58');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (17, null, 334, 'in purus eu magna vulputate luctus cum', '2017-01-29 04:13:33');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (17, null, 333, 'diam cras pellentesque volutpat dui maecenas tristique', '2017-01-12 07:40:55');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (17, null, 327, 'consequat lectus in est risus auctor', '2017-01-16 16:31:57');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (54, null, 323, 'commodo vulputate justo in blandit ultrices', '2017-01-03 14:51:10');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (13, null, 330, 'tortor sollicitudin mi sit amet lobortis sapien sapien non', '2017-01-14 03:22:53');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (55, null, 333, 'morbi odio odio elementum eu interdum eu', '2017-01-22 16:59:10');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (16, null, 331, 'imperdiet et commodo vulputate justo in blandit ultrices', '2017-01-28 15:43:37');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (16, null, 332, 'rhoncus sed vestibulum sit amet cursus id', '2017-01-04 06:45:15');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (55, null, 339, 'mi nulla ac enim in tempor turpis nec euismod', '2017-01-24 22:38:29');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (18, null, 338, 'etiam faucibus cursus urna ut tellus nulla', '2017-01-19 04:13:31');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (16, null, 338, 'sit amet justo morbi ut', '2017-01-25 11:14:24');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (53, null, 322, 'nulla pede ullamcorper augue a suscipit nulla elit', '2017-01-01 03:19:04');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (18, null, 332, 'bibendum morbi non quam nec dui luctus', '2017-01-14 01:57:14');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (17, null, 337, 'posuere cubilia curae mauris viverra diam vitae quam suspendisse', '2017-01-06 12:48:45');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (13, null, 327, 'nisl aenean lectus pellentesque eget nunc donec quis orci eget', '2017-01-19 00:50:14');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (13, null, 322, 'orci eget orci vehicula condimentum curabitur in', '2017-01-24 12:41:35');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (55, null, 328, 'nec dui luctus rutrum nulla tellus in sagittis', '2017-01-12 07:09:50');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (53, null, 332, 'vulputate justo in blandit ultrices enim lorem ipsum dolor sit', '2017-01-20 16:18:17');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (55, null, 321, 'mollis molestie lorem quisque ut erat curabitur', '2017-01-01 10:14:59');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (55, null, 322, 'felis eu sapien cursus vestibulum', '2017-01-30 05:16:58');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (54, null, 332, 'morbi vestibulum velit id pretium iaculis', '2017-01-30 15:37:54');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (17, null, 336, 'aliquam quis turpis eget elit sodales scelerisque mauris sit amet', '2017-01-29 13:53:21');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (16, null, 332, 'elit sodales scelerisque mauris sit amet eros suspendisse accumsan tortor', '2017-01-06 13:49:09');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (16, null, 325, 'in hac habitasse platea dictumst maecenas ut massa', '2017-01-18 05:41:59');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (13, null, 325, 'suscipit nulla elit ac nulla sed', '2017-01-06 18:34:21');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (17, null, 325, 'in felis donec semper sapien a libero', '2017-01-23 15:53:08');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (54, null, 332, 'felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet', '2017-01-17 21:20:21');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (18, null, 327, 'ipsum dolor sit amet consectetuer adipiscing elit proin interdum', '2017-01-06 06:08:41');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (54, null, 326, 'ridiculus mus etiam vel augue vestibulum rutrum rutrum', '2017-01-20 21:04:38');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (54, null, 320, 'aliquam erat volutpat in congue etiam justo etiam pretium iaculis', '2017-01-23 00:07:46');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (55, null, 329, 'donec dapibus duis at velit eu est congue', '2017-01-23 04:04:57');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (13, null, 333, 'nulla justo aliquam quis turpis', '2017-01-17 09:56:38');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (18, null, 327, 'ac diam cras pellentesque volutpat dui maecenas tristique est et', '2017-01-25 18:28:20');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (18, null, 330, 'aliquet maecenas leo odio condimentum id', '2017-01-10 08:19:21');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (17, null, 329, 'rutrum neque aenean auctor gravida', '2017-01-24 23:25:01');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (16, null, 330, 'ridiculus mus etiam vel augue vestibulum rutrum', '2017-01-02 01:03:06');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (13, null, 335, 'in lacus curabitur at ipsum ac tellus semper interdum', '2017-01-21 08:17:37');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (53, null, 326, 'tellus semper interdum mauris ullamcorper purus sit', '2017-01-27 06:28:54');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (18, null, 328, 'ut mauris eget massa tempor convallis nulla neque libero', '2017-01-19 11:17:32');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (13, null, 337, 'ornare consequat lectus in est risus auctor sed', '2017-01-17 10:09:25');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (53, null, 337, 'at turpis a pede posuere', '2017-01-05 04:16:18');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (13, null, 321, 'feugiat non pretium quis lectus suspendisse', '2017-01-20 06:08:41');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (13, null, 335, 'tempor turpis nec euismod scelerisque quam turpis', '2017-01-13 07:32:09');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (17, null, 330, 'massa volutpat convallis morbi odio odio elementum eu', '2017-01-20 17:28:17');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (53, null, 328, 'maecenas leo odio condimentum id luctus nec', '2017-01-11 10:00:22');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (53, null, 338, 'integer non velit donec diam neque vestibulum eget vulputate ut', '2017-01-10 16:19:53');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (55, null, 338, 'nulla tempus vivamus in felis eu', '2017-01-07 15:10:01');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (54, null, 333, 'quis libero nullam sit amet turpis elementum ligula vehicula consequat', '2017-01-01 20:44:35');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (18, null, 334, 'eleifend donec ut dolor morbi vel lectus in quam', '2017-01-12 21:20:30');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (17, null, 320, 'eu felis fusce posuere felis sed lacus', '2017-01-17 00:43:28');
insert into message (sender_id, recipient_id, topic_id, text, date_and_time) values (18, null, 327, 'lectus in est risus auctor sed tristique in', '2017-01-02 12:44:28');

insert into history (column_name, current_value, date_of_last_change, changer_id, main_row_id) values ('title', 'First title', '2017/02/09', 101, 113);
insert into history (column_name, current_value, date_of_last_change, changer_id, main_row_id) values ('title', 'Second title', '2017/02/10', 101, 113);
insert into history (column_name, current_value, date_of_last_change, changer_id, main_row_id) values ('title', 'Third title', '2017/02/11', 101, 113);
insert into history (column_name, current_value, date_of_last_change, changer_id, main_row_id) values ('description', 'First description', '2017/02/12', 101, 113);

insert into history (column_name, current_value, date_of_last_change, changer_id, main_row_id) values ('title', 'First title', '2017/02/11', 44, 313);
insert into history (column_name, current_value, date_of_last_change, changer_id, main_row_id) values ('title', 'Second title', '2017/02/12', 44, 313);
insert into history (column_name, current_value, date_of_last_change, changer_id, main_row_id) values ('description', 'First description', '2017/02/13', 44, 313);

insert into history (column_name, current_value, date_of_last_change, changer_id, main_row_id) values ('title', 'First title', '2017/02/11', 101, 213);
insert into history (column_name, current_value, date_of_last_change, changer_id, main_row_id) values ('title', 'Second title', '2017/02/12', 101, 213);
insert into history (column_name, current_value, date_of_last_change, changer_id, main_row_id) values ('description', 'Second description', '2017/02/12', 101, 213);
